### ISSUE TITLE
Clean up grammar and capitalization errors

### ISSUE THREAD

**Issue by JorySmith** [JorySmith/Albert#15]

**Comment by Aneal07** [comment]
Assign me this, please.

**Comment by JorySmith** [comment]
> Assign me this, please.

Here are the instructions:
"How to Submit a Pull Request"
 https://www.freecodecamp.org/news/how-to-contribute-to-open-source-projects-beginners-guide/#:~:text=How%20to%20Submit%20a%20Pull%20Request
