### ISSUE TITLE
Add quotes to techniques and principles where needed

### ISSUE THREAD

**Issue by JorySmith** [JorySmith/Albert#18]

**Comment by RajeevDash007** [comment]
We can add a quote above the about section,
assign me this issue so that I can fix it

**Comment by JorySmith** [comment]
I'm more looking at adding quote citations to techniques and principles section that don't have any or just one,such as:
Organize and Structure your Mind
Provide Demonstrations and Examples over Explanations
Test Ideas and Solutions

Does that make sense?

**Comment by JorySmith** [comment]
> We can add a quote above the about section, assign me this issue so that I can fix it

For example, try adding this quote citation to "Test Ideas and Solutions":
"Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So, throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails. Explore, Dream, Discover."  - Mark Twain

**Comment by RajeevDash007** [comment]
> > We can add a quote above the about section, assign me this issue so that I can fix it
> 
> For example, try adding this quote citation to "Test Ideas and Solutions": "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So, throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails. Explore, Dream, Discover." - Mark Twain

should I add the quote after the para of test ideas and solutions? @JorySmith

**Comment by JorySmith** [comment]
Yea @RajeevDash007 so this will be citation number "2" There is already a citation number "1" so this new citation will come just after the first one.
![Screenshot 2023-07-18 1 28 23 PM](https://github.com/JorySmith/Albert/assets/46983170/fd321f95-de4f-4948-b782-c495b11e57ea)

**Comment by RajeevDash007** [comment]
K, will do that and create a pull request
